ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-token-keys/access-token-public.key"
SQL_USERNAME: "postgres"
SQL_PASSWORD: "nart123"
SQL_HOST: "localhost"
SQL_PORT: "5432"
SQL_DB: "simple_note"