access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${SQL_HOST}:${SQL_PORT}/${SQL_DB}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG